server:
  port: 8080

spring:
  datasource:
    username: root
    password: xiaoyao1A123
    url: jdbc:mysql://127.0.0.1:3306/goods_tag?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:/mapper/*.xml


